TRUNCATE USER_ROLE;
INSERT INTO USER_ROLE(UR_USER_NAME,UR_ROLE_NAME,UR_ROLE_ACTION) VALUES('alex','rdb_role','read');
INSERT INTO USER_ROLE(UR_USER_NAME,UR_ROLE_NAME,UR_ROLE_ACTION) VALUES('john','rdb_role','edit');
INSERT INTO USER_ROLE(UR_USER_NAME,UR_ROLE_NAME,UR_ROLE_ACTION) VALUES('john','rdb_role','admin');
INSERT INTO USER_ROLE(UR_USER_NAME,UR_ROLE_NAME,UR_ROLE_ACTION) VALUES('alex','spark_role','admin');
INSERT INTO USER_ROLE(UR_USER_NAME,UR_ROLE_NAME,UR_ROLE_ACTION) VALUES('alex','spark_role','read');
INSERT INTO USER_ROLE(UR_USER_NAME,UR_ROLE_NAME,UR_ROLE_ACTION) VALUES('john','spark_role','edit');

