DROP TABLE IF EXISTS USER_ROLE;
DROP SEQUENCE IF EXISTS UR_USER_ROLE_PK_SEQ;
CREATE SEQUENCE UR_USER_ROLE_PK_SEQ;
CREATE TABLE USER_ROLE(
            UR_ID INTEGER DEFAULT NEXTVAL('UR_USER_ROLE_PK_SEQ'),
            UR_USER_NAME VARCHAR(255),
            UR_ROLE_NAME VARCHAR(255),
            UR_ROLE_ACTION VARCHAR(255),
            UNIQUE (UR_USER_NAME, UR_ROLE_NAME, UR_ROLE_ACTION),
            PRIMARY KEY (UR_ID)
);